language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
 - pip install --user cpp-coveralls

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - export CXX_FLAGS="${CXX_FLAGS} --coverage -g -O0"
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DBUILD_TESTS=ON .. 
  - make
  - ctest

after_success:
 - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
